- hosts: remote
  gather_facts: false
  vars:
    src: test
    dest: /home/ansible_user/test
  tasks :
    - name: copy file to remote server
      copy:
        src : "{{ src }}"
        dest: "{{ dest }}"
